-- Listing the orders given by city as a total
SELECT
CT.CITY SEHIR ,SUM(O.TOTALPRICE) TOPLAM_SIPARIS,COUNT(O.ID) SIPARIS_ADEDI
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY ORDER BY SIPARIS_ADEDI DESC

-- Order distribution by product categories
SELECT
I.CATEGORY1 CAT1,I.CATEGORY2 CAT2,SUM(OD.LINETOTAL) SIPARIS_TUTARI
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
GROUP BY I.CATEGORY1,I.CATEGORY2  ORDER BY 1,3

-- Order distribution by customers
 SELECT U.NAMESURNAME MUSTERI_ADI,SUM(O.TOTALPRICE) SIPARIS_TOPLAMI , COUNT(O.ID) ALISVERIS_SAYISI
 FROM ORDERS O
 JOIN USERS U ON U.ID=O.USERID
 GROUP BY U.NAMESURNAME
 HAVING SUM(O.TOTALPRICE)>=1000
 ORDER BY 2 DESC

-- Order distribution by gender of customers
 CASE
 WHEN U.GENDER='E' THEN 'ERKEK'
   ELSE 'KADIN'
   END AS CINSIYET , SUM(O.TOTALPRICE) SIPARIS_TOPLAMI,COUNT(O.ID) ALISVERIS_SAYISI
 FROM ORDERS O
 JOIN USERS U ON U.ID=O.USERID
 GROUP BY U.GENDER

 -- Order distribution by payment type
SELECT
CASE
  WHEN P.PAYMENTTYPE='1' THEN 'KREDI_KARTI'
  ELSE 'NAKIT'
  END AS 'ODEME_TURU ' , SUM(O.TOTALPRICE) SIPARIS_TOPLAMI
 FROM ORDERS O
 JOIN PAYMENTS P ON P.ORDERID=O.ID
 GROUP BY P.PAYMENTTYPE

-- Order distribution of cities by days of the week
 SET LANGUAGE Turkish
 SELECT  CT.CITY SEHIR ,DATENAME(DW,O.DATE_) GUN ,SUM(O.TOTALPRICE) SIPARIS_TUTARI
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 JOIN CITIES CT ON CT.ID=A.CITYID
 GROUP BY CT.CITY,DATENAME(DW,O.DATE_),DATEPART(DW,O.DATE_)
 ORDER BY 1,DATEPART(DW,O.DATE_)

-- Average shipping times of cities
SELECT
CT.CITY SEHİR ,  AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) SAAT
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY

-- Order distribution by age groups
SELECT YASARALIGI,SUM(SIPARISTOPLAMI) SIPARIŞTOPLAMI
 FROM
 (SELECT DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,
  CASE
     WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 41 AND 50 THEN '41-50 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 51 AND 60 THEN '51-60 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 61 AND 70 THEN '61-70 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 71 AND 80 THEN '71-80 YAS ARASI'
	 WHEN DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) >80 THEN '80 PLUS'
  END AS YASARALIGI ,
  SUM(O.TOTALPRICE)SIPARISTOPLAMI
 FROM USERS U
 JOIN ORDERS O ON USERID=U.ID
 GROUP BY DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()))T
 GROUP BY YASARALIGI

--Product Analysis
SELECT
I.ITEMCODE URUN_KODU ,I.ITEMNAME URUN_ADI ,I.BRAND MARKA,I.CATEGORY1 CAT1,I.CATEGORY2 CAT2 ,
MIN(O.DATE_) ILK_SATIS_TARIHI,MAX(O.DATE_) SON_SATIS_TARIHI,
MIN(OD.UNITPRICE) ENDUSUKFIYAT, MAX(OD.UNITPRICE) EN_YUKSEK_FIYAT, AVG(OD.UNITPRICE) ORTALAMA_FIYAT,
SUM(OD.LINETOTAL) CIRO , SUM(OD.AMOUNT)MIKTAR
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
JOIN ORDERS O ON O.ID=OD.ORDERID
GROUP BY I.ITEMCODE ,I.ITEMNAME  ,I.BRAND ,I.CATEGORY1 ,I.CATEGORY2
ORDER BY 1

-- The address where the customer made the last purchase
  SELECT U.ID,U.NAMESURNAME,
  (
  SELECT  TOP 1 A.ADDRESSTEXT  FROM ORDERS O
  JOIN ADDRESS A ON A.ID=U.ID
  WHERE O.USERID=1 ORDER BY O.DATE_ DESC
  )
  FROM USERS U

